INSERT INTO categories ( id, term, category, hidden, deleted) VALUES
  (1,'ska','ska',0,0),
  (2,'metal','metal',0,0),
  (3,'rock','rock',0,0);

INSERT INTO term_weight (term, weight, deleted) VALUES
  ('club'    , 0.1,  0),
  ('bar'     , 0.1,  0),
  ('lounge'  , 0.1,  0),
  ('e.v.'    , 0.1,  0),
  ('Gelände' , 0.2,  0),
  ('alter'   , 0.1,  0),
  ('alte'    , 0.1,  0),
  ('altes'   , 0.1,  0),
  ('dresden' , 0.05, 0),
  ('live'    , 0.01, 0);

INSERT INTO pattern (id, type, name, url, starturl, icon, pattern, subpattern, dateformat, countrycode, deleted, hidden) VALUES
  ( 1, 'webharvest', 'groovestation',    'http://www.groovestation.de/',      'live.html',          'http://www.groovestation.de/favicon.ico', E'<loop item="event" index="i">  <list>  <xpath	expression=\'//div[@id="main_content"]/div[@class="live"]\'> 	<html-to-xml treatdeprtagsascontent="1"  	treatunknowntagsascontent="1">   <http url="${baseUrl}${startUrl}">   </http> </html-to-xml>	</xpath>  </list> 	<!-- downloads each article and extract data from it --> 	<body>	<empty> 	<var-def name="test">  	<xpath    expression=\'//div[@class="live_head"]/div[@class="head_content"]/table/tbody/tr/td/p/text()\'>	<var name="event" />    </xpath></var-def>  	</empty> 	 <case>    <if condition=\'${startDate.toString().equals(test.toString())}\'>  <template>   	 <![CDATA[<article>]]>     <![CDATA[<title>]]><xpath  	expression=\'//div[@class="live_head"]/div[@class="head_content"]/table/tbody/tr/td/p/span[@class="white"]/text()\'><var   name="event" /></xpath><![CDATA[</title>]]>  <![CDATA[<picture>]]>${baseUrl}<xpath	expression=\'//div[@class="live_content"]/p/img/@src\'> 	<var name="event" />   	</xpath>	<![CDATA[</picture>]]><![CDATA[<date>]]>${startDate}<![CDATA[</date>]]><![CDATA[<location>]]>Groovestation<![CDATA[</location>]]><![CDATA[<sourcelink>]]>${baseUrl}<![CDATA[</sourcelink>]]>  	<![CDATA[</article>]]>    </template> </if>    </case> </body></loop>', null, 'EEEE, dd. MMMM', 'DE_de', 0, 0),
  ( 2, 'webharvest', 'DoubleD_Town',     'http://www.doubled-town.de/forum/', 'viewforum.php?f=20', 'http://www.doubled-town.de/favicon.ico', E'<loop item="articleUrl" index="i">  <list> <loop item="linkTags" filter="unique">  	<list>	   <xpath expression=\'//div[@class="mForumMain mForumMainItemBorderSmall"]/div[@class="mForumMainItem"]/div[@class="mForumMainItemText"]/span/a[@class="topictitle"]\'>    <html-to-xml treatdeprtagsascontent="1"   treatunknowntagsascontent="1">   <http url="${baseUrl}${startUrl}">   </http></html-to-xml>   	</xpath>	</list>   <body> <regexp>	    <regexp-pattern>([0-9]{2}\.[0-9]{2}\.[0-9]{2})</regexp-pattern>     <regexp-source>        <var name="linkTags" />   	    </regexp-source>   	    <regexp-result>                <case>            <if condition=\'${startDate.toString().equals(_1.toString())}\'>             <xpath expression="a/@href">  	            	<var name="linkTags" />  	            	</xpath>        </if>        </case>    </regexp-result>   	</regexp>   </body> 	</loop></list><!-- downloads each article and extract data from it --> 	<body>  	<template> 	            <![CDATA[<article>]]>       <call name="DoubleD_Town_Sub01">           <call-param name="pageUrl"><template>${baseUrl}${articleUrl}</template></call-param>   	</call><![CDATA[<sourcelink>]]>${baseUrl}<![CDATA[</sourcelink>]]> 	            <![CDATA[</article>]]>             </template>	</body> 	</loop>', E'<function name="DoubleD_Town_Sub01"><return><template><![CDATA[<sourcelink>${sys.escapeXml(pageUrl.toString())}</sourcelink>]]></template> <empty> <var-def name="siteSnippet"> <html-to-xml advancedxmlescape="0" treatdeprtagsascontent="1" unicodechars="0" treatunknowntagsascontent="1" allowhtmlinsideattributes="1"> 	<http url="${pageUrl}" />  </html-to-xml> </var-def> </empty> 	<template>            <![CDATA[<title>]]>            	<xpath expression="normalize-space(data(//div[2]/div[4]/div/div/span/b))"> <var name="siteSnippet"/> </xpath>            <![CDATA[</title>]]>            <![CDATA[<date>]]>            	<xpath expression=\'normalize-space(data(//div[2]/div[6]/div[1]/div[@class="mPostMainItemText"]/span))\'>  	<var name="siteSnippet"/>  </xpath>            <![CDATA[</date>]]>            <![CDATA[<price>]]>            	<xpath expression=\'normalize-space(data(//div[2]/div[6]/div[2]/div[@class="mPostMainItemText"]/span))\'> <var name="siteSnippet"/></xpath> 	<![CDATA[</price>]]>                        <![CDATA[<location>]]>            	<xpath expression=\'normalize-space(data(//div[2]/div[6]/div[3]/div[@class="mPostMainItemText"]/span))\'><var name="siteSnippet"/>  </xpath>            <![CDATA[</location>]]>            <![CDATA[<picture>]]><xpath expression=\'normalize-space(data(//div[3]/div[3]/a/@href))\'><var name="siteSnippet"/></xpath><![CDATA[#.jpg</picture>]]> </template></return></function>', 'dd.MM.yy', 'DE_de', 0, 0);