language: java
before_install:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c "alter user postgres WITH PASSWORD 'test';" -U postgres


env: DATABASE_URL=postgres://postgres:test@localhost/travis_ci_test

notifications:
  irc: "chat.freenode.net#l-ray"
